- name: installation-gatsby

  hosts: targetes

  become: true

  tasks:

    - name: Installer Node.js et npm
      ansible.builtin.yum:                    #https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_module.html
        name:
          - gcc-c++
          - make
        state: present

    - name: Installer Nodejs
      ansible.builtin.yum:
        name:
          - nodejs
    - name: Installer gatsby-cli
      npm:
        name: gatsby-cli
        
