- name: installation-gatsby

  hosts: targetes

  become: true

  tasks:
    - name: Installer Node.js et npm
      apt:
        name: ["node.js", "npm"]
        state: present

    - name: Clonner le référentiel Gatsby
      git:
        repo: ["node.js", "npm"]
        dest: https://github.com/gatsbyjs/gatsby-starter-default
        update: true

    - name: Installer les dépendances
      command: npm install
      arg: 
        chdir: ./gatsby-cli

    - name: construire le site Gatsby
      command: npm run build
      arg: 
        chdir: ./gatsby-cli

    - name: démarer le serveur Gatsby
      command: npm run start
      arg: 
        chdir: ./gatsby-cli
